/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication.airline;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
/**
 *
 * @author RAJEEV
 */
public class Details extends javax.swing.JFrame {
String flightname1;
String date1;
int flightid1;
String class1;
Ticket t = new Ticket();
    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        fullname = new javax.swing.JTextField();
        age = new javax.swing.JSpinner();
        phone = new javax.swing.JFormattedTextField();
        addpassenger = new javax.swing.JButton();
        generate = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 102));
        jLayeredPane1.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Go Airlines...");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\RAJEEV\\Documents\\NetBeansProjects\\airline\\logo.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Personal Information");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Full Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Age");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Gender");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Phone No.");

        gender.add(male);
        male.setText("Male");

        gender.add(female);
        female.setText("Female");

        gender.add(other);
        other.setText("Other");

        fullname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        phone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        jLayeredPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(male, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(female, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(other, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(fullname, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(age, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(phone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane2Layout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(37, 37, 37)
                        .addComponent(female)
                        .addGap(38, 38, 38)
                        .addComponent(other))
                    .addComponent(fullname)
                    .addComponent(age)
                    .addComponent(phone, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(male)
                    .addComponent(female)
                    .addComponent(other))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        addpassenger.setBackground(new java.awt.Color(0, 0, 102));
        addpassenger.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        addpassenger.setForeground(new java.awt.Color(255, 255, 255));
        addpassenger.setText("Add  more Passenger");
        addpassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpassengerActionPerformed(evt);
            }
        });

        generate.setBackground(new java.awt.Color(0, 0, 102));
        generate.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        generate.setForeground(new java.awt.Color(255, 255, 255));
        generate.setText("Generate Ticket");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(0, 0, 102));
        clear.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addpassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addpassenger, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void takeFlightNameAndId(Object nameOfFlight, Object flightid){
        flightname1 =(String) nameOfFlight;
        flightid1 = (int)flightid;
    }
    public void dateAndClass(String d, String class2){
    date1 = d;
    class1 = class2;
    }
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       
        fullname.setText("");
       age.setValue(0);
       phone.setText("");
       male.setSelected(false);
       female.setSelected(false);
       other.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
      try{
        
          String FN= (String)fullname.getText();
       int Age = (int)age.getValue();
      String gender1 = "";
       if (male.isSelected()){
       gender1 = "M";
      }else if (female.isSelected()){
       gender1 = "F";
      }else if (other.isSelected()){
       gender1 = "Other";
      }
      long Phone = (long)phone.getValue();
      
       t.setpassenger( FN, Age, gender1, Phone);
       t.printFlightName(flightname1);
       t.setVisible(true);
       t.setdate(date1);
       
       Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?characterEncoding=UTF-8","root","");
     
                if (con != null) {
                    System.out.println("Connection to the database has been established.");
                
                     // You can now perform database operations here.
                    // create.Statement() creates statement object which is responsible for executing queries on table 
                    Statement stmt = con.createStatement();
                    String query = "INSERT INTO passenger_details(flight_id,passenger_name, passenger_age, gender, phone_no) values (?,?,?,?,?);";
                    PreparedStatement preparedStatement = con.prepareStatement(query);
                   
            // Set the parameter values
                preparedStatement.setInt(1, flightid1);
                preparedStatement.setString(2,FN);
                preparedStatement.setInt(3,Age);
                preparedStatement.setString(4,gender1);
                preparedStatement.setLong(5,Phone);
               int rowsAffected = preparedStatement.executeUpdate();
                    preparedStatement.close();
               //reduce the available seats
                    //Statement stmt1 = con.createStatement();
                    if (class1 == "Economy"){
                     String query1 = "UPDATE flight_details SET available_seats_economy = available_seats_economy - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }else  if (class1 == "Business"){
                     String query1 = "UPDATE flight_details SET available_business = available_business - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }else  if (class1 == "Premium Economy"){
                     String query1 = "UPDATE flight_details SET premium_economy = premium_economy - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }else  if (class1 == "First Class"){
                     String query1 = "UPDATE flight_details SET available_first_class = available_first_class - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }
                } 
       }catch(Exception e){
               System.out.println(e);
               }
       
       
    }//GEN-LAST:event_generateActionPerformed

    private void addpassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpassengerActionPerformed
         try{
        
          String FN= (String)fullname.getText();
       int Age = (int)age.getValue();
      String gender1 = "";
       if (male.isSelected()){
       gender1 = "M";
      }else if (female.isSelected()){
       gender1 = "F";
      }else if (other.isSelected()){
       gender1 = "Other";
      }
      long Phone = (long)phone.getValue();
      
       t.setpassenger( FN, Age, gender1, Phone);
       
      
       t.setdate(date1);
      
       
       Class.forName("com.mysql.cj.jdbc.Driver");  
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/airline?characterEncoding=UTF-8","root","");
     
                if (con != null) {
                    System.out.println("Connection to the database has been established.");
                
                     // You can now perform database operations here.
                    // create.Statement() creates statement object which is responsible for executing queries on table 
                    Statement stmt = con.createStatement();
                    String query = "INSERT INTO passenger_details(flight_id,passenger_name, passenger_age, gender, phone_no) values (?,?,?,?,?);";
                    PreparedStatement preparedStatement = con.prepareStatement(query);

            // Set the parameter values
                preparedStatement.setInt(1, flightid1);
                preparedStatement.setString(2,FN);
                preparedStatement.setInt(3,Age);
                preparedStatement.setString(4,gender1);
                preparedStatement.setLong(5,Phone);
               int rowsAffected = preparedStatement.executeUpdate();
                    preparedStatement.close();
                     if (class1 == "Economy"){
                     String query1 = "UPDATE flight_details SET available_seats_economy = available_seats_economy - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }else  if (class1 == "Business"){
                     String query1 = "UPDATE flight_details SET available_business = available_business - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }else  if (class1 == "Premium Economy"){
                     String query1 = "UPDATE flight_details SET premium_economy = premium_economy - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }else  if (class1 == "First Class"){
                     String query1 = "UPDATE flight_details SET available_first_class = available_first_class - 1 WHERE flight_id = '"+ flightid1 +"';";
                     PreparedStatement p1 = con.prepareStatement(query1);
                     int rowsAffect = p1.executeUpdate();
                     p1.close();
                    }
                } 
       }catch(Exception e){
               System.out.println(e);
               }
       fullname.setText("");
       age.setValue(0);
       phone.setText("");
       male.setSelected(false);
       female.setSelected(false);
       other.setSelected(false);
    }//GEN-LAST:event_addpassengerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    
                }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpassenger;
    private javax.swing.JSpinner age;
    private javax.swing.JButton clear;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fullname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton generate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JRadioButton other;
    private javax.swing.JFormattedTextField phone;
    // End of variables declaration//GEN-END:variables

             
}

